-- Fleet service-parts verification V3 — 2026-09-27
-- References verified by supplier/manufacturer catalogs. Physical fitment remains candidate.

with src(plate,source_key,source_type,title,publisher,publication_year,source_url,authority_level,applicability_status,access_status,verification_status,notes,source_metadata) as (
 values
 ('CPI6C79','mann_filters_vw_9150eod_mwm412_v3','application_catalog','MANN-FILTER application data — VW 9.150 E OD / MWM 4.12 TCAE','MANN+HUMMEL',2026,'https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/w962_mann-filter.html','oem_supplier','exact_variant_family','public_full','verified','Confirms W 962 oil filter for 9.150 E OD / MWM 4.12 TCAE, 04/2004–12/2012. Cross-checked with WK 962/13 and C 17 308 product applications.',jsonb_build_object('checked_at','2026-09-27','evidence_urls',jsonb_build_array('https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/w962_mann-filter.html','https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/wk962/13_mann-filter.html','https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/c17308_mann-filter.html'))),
 ('MBJ1166','tecfil_filters_volare_a6_2000_v3','application_catalog','Tecfil application catalog — Volare A6 MWM 4.07 TCA 01/2000–12/2001','Tecfil',2026,'https://catalogo.tecfil.com.br/?pagina=5','catalog_supplier','exact_model_year_engine_family','public_full','verified','Exact year-window table confirms ARS3003, ASR203, PSL340, PSC498 and PSD970/1 for Volare A6 MWM 4.07 TCA 01/2000–12/2001.',jsonb_build_object('checked_at','2026-09-27','year_window','01/2000-12/2001','engine','MWM 4.07 TCA')),
 ('MBJ1166','mann_filters_volare_a6_crossrefs_v3','application_catalog','MANN-FILTER cross references — Volare A6 MWM 4.07 TCA','MANN+HUMMEL',2026,'https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/w1323_mann-filter.html','oem_supplier','model_engine_family','public_full','verified','Confirms W 1323 oil and WK 842/3 fuel applications to Volare A6 / MWM 4.07 TCA; cross-reference only.',jsonb_build_object('checked_at','2026-09-27','fuel_url','https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/wk842/3_mann-filter.html')),
 ('BYH8J61','mann_filters_mercedes_608_om314_v3','application_catalog','MANN-FILTER heavy application data — Mercedes 608 / OM314','MANN+HUMMEL',2026,'https://www.mann-filter.com/content/dam/website/mann-filter/mann-filter-com/br-pt/documents/cat%C3%A1logo/catalogo_mann_filter_PESADA_2022_2023_web.pdf','oem_supplier','model_engine_family','public_full','verified','608 L-D/E/O / OM314 01/1973–12/1983: C 13 114/4, PU 707 x, BFU 707 and CF 600. PF 1155 K independently confirmed for L 608 D / OM314.',jsonb_build_object('checked_at','2026-09-27','oil_filter_url','https://www.mann-filter.com/en/catalog/search-results/product.html/pf1155k_mann-filter.html','air_filter_url','https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/c13114/4_mann-filter.html','fuel_filter_url','https://www.mann-filter.com/br-pt/catalogo/resultados-da-pesquisa/produto.html/pu707x_mann-filter.html')),
 ('BYH8J61','frasle_clutch_lining_608_om314_v3','application_catalog','Fras-le clutch lining application catalog — Mercedes-Benz 608 OM314','Fras-le',2025,'https://www.fras-le.com/media/1490/catalog-revestimiento-embragues.pdf','oem_supplier','model_engine_family_variant_options','public_full','verified','RC/716 (85 cv) and RC/913 (all), Sachs-system linings. These are lining references, not complete clutch-disc assemblies.',jsonb_build_object('checked_at','2026-09-27','purchase_gate','measure/inspect installed clutch before purchase')),
 ('EJW6A76','sprinter_8ac903662_build_fitment_audit_v3','fitment_audit','Sprinter 8AC903662BE040910 — build-year/EPC reconciliation audit','Oficina 360',2026,null,'internal_reconciliation','exact_vehicle_pending_catalog_reconciliation','internal','reference_pending','CRLV profile: production 2010, model 2011, VIN 8AC903662BE040910. Public W903/903.662 EPC structures often use older production windows/sample VINs; no family reference becomes physical fitment without exact 2010/2011 evidence.',jsonb_build_object('checked_at','2026-09-27','vin','8AC903662BE040910','production_year',2010,'model_year',2011,'rule','do_not_promote_family_epc_to_physical_fitment'))
)
insert into public.v2_vehicle_technical_sources(company_id,vehicle_id,source_key,source_type,title,publisher,publication_year,source_url,authority_level,applicability_status,access_status,verification_status,notes,source_metadata)
select v.company_id,v.id,s.source_key,s.source_type,s.title,s.publisher,s.publication_year,s.source_url,s.authority_level,s.applicability_status,s.access_status,s.verification_status,s.notes,s.source_metadata
from src s join public.v2_vehicles v on upper(replace(v.plate,'-',''))=s.plate
on conflict(company_id,vehicle_id,source_key) do update set source_type=excluded.source_type,title=excluded.title,publisher=excluded.publisher,publication_year=excluded.publication_year,source_url=excluded.source_url,authority_level=excluded.authority_level,applicability_status=excluded.applicability_status,access_status=excluded.access_status,verification_status=excluded.verification_status,notes=excluded.notes,source_metadata=excluded.source_metadata,updated_at=now();

-- VW 9.150 EOD / MWM 4.12 TCE: C 17 308, WK 962/13, W 962.
update public.v2_vehicle_components c set data_status='verified',source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('verification_source_key','mann_filters_vw_9150eod_mwm412_v3','catalog_application','VW 9.150 E OD / MWM 4.12 TCAE / 04-2004 to 12-2012','catalog_reference_verified',true,'physical_fitment_verified',false,'purchase_gate','confirm housing/installed filter before purchase','verified_at','2026-09-27'),updated_at=now()
from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='CPI6C79' and c.name in ('Filtro de ar do motor','Filtro principal de combustivel','Filtro de oleo do motor');
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('mann_part_number','WK 962/13','mwm_original_numbers',jsonb_build_array('9.0541.15.1.0027','905411510042','905411510028')) from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='CPI6C79' and c.name='Filtro principal de combustivel';
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('mann_part_number','C 17 308','vw_original_numbers',jsonb_build_array('2RD 129 620','2VC 129 619','2TA 129 619','2R0 129 620 D')) from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='CPI6C79' and c.name='Filtro de ar do motor';

-- Volare A6 / MWM 4.07 TCA, exact 01/2000–12/2001 Tecfil row.
update public.v2_vehicle_components c set data_status='verified',source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('verification_source_key','tecfil_filters_volare_a6_2000_v3','catalog_application','Volare A6 / MWM 4.07 TCA / 01-2000 to 12-2001','catalog_reference_verified',true,'physical_fitment_verified',false,'purchase_gate','confirm installed housing/filter before purchase','verified_at','2026-09-27'),updated_at=now()
from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='MBJ1166' and c.name in ('Filtro de ar','Elemento de seguranca do filtro de ar','Filtro de oleo','Filtro de combustivel','Separador de agua');
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('cross_references',jsonb_build_array('MANN W 1323','MWM 905411880018','MWM 905411880026','Agrale 6008001204004','VW 062115561A')) from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='MBJ1166' and c.name='Filtro de oleo';
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('cross_references',jsonb_build_array('MANN WK 842/3','Volare/Agrale original 6008.006.035.00.7')) from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='MBJ1166' and c.name='Filtro de combustivel';
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('assembly_note','Tecfil row lists PSD970/1 with CSD01 cup for 01/2000-12/2001 A6') from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='MBJ1166' and c.name='Separador de agua';

-- Mercedes 608 / OM314 service filters.
update public.v2_vehicle_components c set data_status='verified',source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('verification_source_key','mann_filters_mercedes_608_om314_v3','catalog_application','Mercedes 608 / OM314','catalog_reference_verified',true,'physical_fitment_verified',false,'purchase_gate','confirm installed filter housing/element before purchase','verified_at','2026-09-27'),updated_at=now()
from public.v2_vehicle_component_links l join public.v2_vehicles v on v.id=l.vehicle_id where l.component_id=c.id and v.plate='BYH8J61' and c.name in ('Filtro de ar seco','Elemento de seguranca do filtro de ar','Filtro de combustivel','Pre-filtro de combustivel','Filtro de oleo');

-- Fras-le catalog options: lining only, never the whole clutch disc.
with ins(name,mpn,thickness_mm,holes_pass,holes_countersunk,notes) as (values
 ('Revestimento de embreagem Fras-le RC/716','RC/716',3.50,18,12,'608 OM-314 85 CV, Sachs, 250 x 165 mm; inspect installed variant.'),
 ('Revestimento de embreagem Fras-le RC/913','RC/913',4.20,20,20,'608 OM-314, all, Sachs, 250 x 165 mm; inspect installed variant.'))
insert into public.v2_vehicle_components(group_code,name,generic_name,oem_brand,manufacturer_part_number,location_description,function_description,data_status,component_type,dimensions_spec,replacement_notes,source_metadata)
select 'transmission',i.name,'revestimento/lona do disco de embreagem','Fras-le',i.mpn,'Disco de embreagem, entre motor e cambio','Material de atrito rebitado no disco; not a complete disc assembly','verified','consumable',jsonb_build_object('outer_diameter_mm',250,'inner_diameter_mm',165,'thickness_mm',i.thickness_mm,'through_holes',i.holes_pass,'countersunk_holes',i.holes_countersunk,'system','Sachs'),jsonb_build_array('Confirmar espessura, furacao e sistema instalado','Nao tratar como kit/disco completo'),jsonb_build_object('seed','fleet_service_parts_verification_v3','verification_source_key','frasle_clutch_lining_608_om314_v3','catalog_reference_verified',true,'physical_fitment_verified',false,'orderable',false,'notes',i.notes)
from ins i where not exists(select 1 from public.v2_vehicle_components c where c.manufacturer_part_number=i.mpn and c.source_metadata->>'verification_source_key'='frasle_clutch_lining_608_om314_v3');
insert into public.v2_vehicle_component_applications(component_id,chassis_family,chassis_variant,engine_family,engine_code,notes,fitment_status,source_metadata)
select c.id,'Mercedes-Benz 608','LO 608','Mercedes-Benz OM314','OM314','Catalog reference verified; installed lining not physically confirmed.','candidate',jsonb_build_object('source_key','frasle_clutch_lining_608_om314_v3','physical_confirmation_required',true) from public.v2_vehicle_components c where c.source_metadata->>'verification_source_key'='frasle_clutch_lining_608_om314_v3' and not exists(select 1 from public.v2_vehicle_component_applications a where a.component_id=c.id and a.chassis_variant='LO 608');
insert into public.v2_vehicle_component_links(company_id,vehicle_id,component_id,fitment_status,notes)
select v.company_id,v.id,c.id,'candidate','Fras-le catalog application to 608 OM314; confirm installed clutch dimensions.' from public.v2_vehicles v cross join public.v2_vehicle_components c where v.plate='BYH8J61' and c.source_metadata->>'verification_source_key'='frasle_clutch_lining_608_om314_v3' on conflict(company_id,vehicle_id,component_id) do nothing;
with target_view as (select ev.id from public.v2_vehicle_exploded_views ev where ev.group_code='transmission' and (ev.source_metadata->>'plate'='BYH8J61' or ev.chassis_variant ilike '%30830311268441%' or ev.chassis_variant='LO 608') order by case when ev.source_metadata->>'plate'='BYH8J61' then 0 else 1 end,ev.created_at limit 1), numbered as (select c.id,row_number() over(order by c.manufacturer_part_number) rn from public.v2_vehicle_components c where c.source_metadata->>'verification_source_key'='frasle_clutch_lining_608_om314_v3')
insert into public.v2_vehicle_exploded_view_items(exploded_view_id,component_id,item_number,quantity,component_type,position_note,exactness_status,source_metadata)
select tv.id,n.id,'CAT-CLUTCH-'||lpad(n.rn::text,2,'0'),1,'consumable','Catalog-option lining; physical fitment pending','verified',jsonb_build_object('source_key','frasle_clutch_lining_608_om314_v3','catalog_position_internal',true) from target_view tv cross join numbered n where not exists(select 1 from public.v2_vehicle_exploded_view_items e where e.exploded_view_id=tv.id and e.component_id=n.id);

update public.v2_vehicle_technical_profiles p set source_metadata=coalesce(p.source_metadata,'{}'::jsonb)||jsonb_build_object('service_parts_research_version','v3','service_parts_reviewed_at','2026-09-27','service_parts_policy','catalog reference verified != physical fitment verified'),updated_at=now() from public.v2_vehicles v where p.vehicle_id=v.id and v.plate in ('CPI6C79','MBJ1166','BYH8J61','EJW6A76');
