with seed(group_code,name,generic_name,oem_part_number,manufacturer_part_number,location_description,function_description,failure_symptoms,diagnostic_notes,required_tools,connector_spec,exploded_view_reference,source_metadata) as (
values
('transmission','Kit de embreagem','kit de embreagem',null,'SACHS 3000 970 079 / 3000 990 437 / LuK 624 3148 09','Entre motor e câmbio manual de cinco marchas.','Transmite o torque do motor ao câmbio e permite desacoplamento nas trocas e partidas.','["patinacao sob carga","trepidacao ao arrancar","pedal pesado ou irregular","dificuldade para engatar marchas"]'::jsonb,'["Confirmar primeiro o código do câmbio e a profundidade/tipo do volante antes de comprar o kit.","Inspecionar disco, platô, rolamento e volante como conjunto.","Se houver ruído apenas com pedal pressionado, investigar rolamento/acionamento antes de condenar todo o kit."]'::jsonb,'["elevador ou fosso","macaco de câmbio","centralizador de embreagem","torquímetro"]'::jsonb,'{}'::jsonb,'Sprinter 313 W903 OM611.981: catálogos listam várias combinações de kit conforme câmbio/volante; aplicação final deve ser confirmada no veículo.','{"seed":"sprinter_w903_chassis_v1","confidence":"catalog_cross_reference","sources":[{"label":"AUTODOC clutch 903.662 OM611.981","url":"https://www.autodoc.parts/car-parts/repair-kit-clutch-complete-10151/mercedes-benz/sprinter/sprinter-3-t-box-903/14839-313-cdi-903-663-903-662-903-661"},{"label":"OnlineCarParts clutch 313 CDI","url":"https://www.onlinecarparts.co.uk/car-brands/spare-parts-mercedes-benz/sprinter-3-t-box-903/14839/10151/repair-kit-clutch-complete.html"}]}'::jsonb),
('transmission','Rolamento de embreagem','rolamento de embreagem','A0002541608',null,'No conjunto de acionamento da embreagem, dentro da campana do câmbio.','Transfere o esforço do acionamento para o platô da embreagem.','["ruido ao pisar na embreagem","pedal áspero","dificuldade de desacoplamento"]'::jsonb,'["Comparar ruído com pedal solto e pressionado.","Ao remover o câmbio, inspecionar guia, garfo e pontos de apoio junto com o rolamento.","Confirmar código do conjunto montado antes da compra."]'::jsonb,'["elevador ou fosso","macaco de câmbio","ferramentas manuais"]'::jsonb,'{}'::jsonb,'PartSouq 903.662: A0002541608 listado no grupo de peças de desacoplamento da embreagem.','{"seed":"sprinter_w903_chassis_v1","confidence":"strong_model_reference","sources":[{"label":"PartSouq 903.662 clutch","url":"https://partsouq.com/en/catalog/genuine/parts?c=Mercedes-Benz&gid=383&q=WDB9036621R317881"}]}'::jsonb),
('transmission','Garfo/acionamento da embreagem','garfo de embreagem','A0002542508',null,'Na campana do câmbio, atuando sobre o rolamento de embreagem.','Converte o movimento do acionamento em deslocamento do rolamento/platô.','["curso de pedal anormal","embreagem nao desacopla totalmente","ruido ou folga no acionamento"]'::jsonb,'["Inspecionar desgaste nos pontos de apoio e contato com o rolamento.","Conferir acionamento hidráulico/cabo conforme versão antes de atribuir a falha ao garfo."]'::jsonb,'["elevador ou fosso","macaco de câmbio","ferramentas manuais"]'::jsonb,'{}'::jsonb,'PartSouq 903.662: A0002542508 listado no conjunto de desacoplamento.','{"seed":"sprinter_w903_chassis_v1","confidence":"strong_model_reference","sources":[{"label":"PartSouq 903.662 clutch","url":"https://partsouq.com/en/catalog/genuine/parts?c=Mercedes-Benz&gid=383&q=WDB9036621R317881"}]}'::jsonb),
('driveline','Mancal central do cardã','suporte/rolamento central do cardã','A9014110312 / A9014110412','DT Spare Parts 4.81450 / MEYLE 034 041 0027','No centro do cardã, preso ao chassi por suporte com rolamento e borracha.','Sustenta o eixo cardã e controla vibração/alinhamento entre câmbio e diferencial.','["vibracao ao acelerar","batida no assoalho","ronco que varia com velocidade","borracha do suporte rasgada"]'::jsonb,'["Marcar a posição/fase das seções do cardã antes de separar.","Inspecionar cruzetas, luvas e balanceamento junto com o mancal.","Confirmar diâmetro interno; há versões de 45 mm e outras configurações."]'::jsonb,'["elevador ou fosso","marcador de posição","extrator/prensa conforme necessidade","torquímetro"]'::jsonb,'{"inner_diameter_common_mm":45}'::jsonb,'A9014110312/A9014110412: suporte central usado em Sprinter W903, incluindo 313 CDI; confirmar geometria do cardã.','{"seed":"sprinter_w903_chassis_v1","confidence":"catalog_cross_reference","sources":[{"label":"OnlineCarParts DT 4.81450","url":"https://www.onlinecarparts.co.uk/dt-9682640.html"},{"label":"AUTODOC A9014110312","url":"https://www.autodoc.parts/car-parts/oem/a9014110312"}]}'::jsonb),
('brakes','Disco de freio dianteiro','disco de freio dianteiro','A9024210612 / A9024210712 / A9024210912','ATE 24.0122-0161.1 / Bosch 0 986 478 849','Eixo dianteiro, entre cubo e pinça.','Fornece superfície de atrito para as pastilhas dianteiras.','["vibracao no pedal ao frear","sulcos ou trincas","espessura abaixo do limite","puxar ao frear"]'::jsonb,'["No 903.662 latino-americano há corte por número de eixo dianteiro entre A9024210612 e A9024210712; não comprar sem conferir.","Medir espessura e empeno com instrumento adequado.","Trocar discos por par no mesmo eixo e avaliar pastilhas/pinças."]'::jsonb,'["paquímetro/micrômetro","relógio comparador","torquímetro","ferramenta de recuo de pinça"]'::jsonb,'{"common_diameter_mm":276,"common_thickness_mm":22,"pcd_mm":130}'::jsonb,'PartSouq 313 903.662 América Latina: A9024210612 até corte de eixo e A9024210712 após corte; catálogos também cruzam A9024210912.','{"seed":"sprinter_w903_chassis_v1","confidence":"axle_cutoff_required","sources":[{"label":"PartSouq 313 903.662 Latin America 2009","url":"https://partsouq.com/es/catalog/genuine/parts?c=Mercedes-Benz&gid=727&q=8AC903662AE024746"},{"label":"AUTODOC brake disc 903.662","url":"https://www.auto-doc.ie/car-parts/brake-disc-10132/mercedes-benz/sprinter/sprinter-3-t-box-903/14839-313-cdi-903-663-903-662-903-661"}]}'::jsonb),
('brakes','Pastilhas de freio dianteiras','jogo de pastilha dianteira','A0044201520 / A0024209920 / A0024203920 / A0044205520',null,'Dentro das pinças do eixo dianteiro.','Geram atrito contra o disco para frenagem do eixo dianteiro.','["ruido ao frear","luz/aviso de desgaste","desgaste desigual","frenagem reduzida"]'::jsonb,'["A referência depende do fabricante/tipo de pinça instalado.","Conferir formato da pastilha e código da pinça antes da compra.","Inspecionar guias e pistões quando houver desgaste desigual."]'::jsonb,'["ferramenta de recuo de pistão","torquímetro","paquímetro"]'::jsonb,'{}'::jsonb,'PartSouq 903.662 lista diferentes jogos conforme sistema de freio; confirmar marca da pinça e código físico.','{"seed":"sprinter_w903_chassis_v1","confidence":"brake_vendor_variant","sources":[{"label":"PartSouq 313 903.662 Latin America 2009","url":"https://partsouq.com/es/catalog/genuine/parts?c=Mercedes-Benz&gid=727&q=8AC903662AE024746"},{"label":"PartSouq W903 front wheel brake","url":"https://partsouq.com/en/catalog/genuine/diagram?c=Mercedes-Benz&number=A0084204920"}]}'::jsonb),
('brakes','Disco de freio traseiro','disco de freio traseiro','A9024230312 / A9024230412 / A9024230512 / A9024230612',null,'Eixo traseiro, entre cubo e pinça.','Fornece superfície de atrito para as pastilhas traseiras.','["vibracao ou pulsacao","ruido traseiro ao frear","sulcos/trincas","espessura abaixo do limite"]'::jsonb,'["No W903 há várias referências conforme número de eixo e fornecedor do freio.","Conferir o código/medidas do disco removido e número de eixo antes da compra.","Trocar discos em par e verificar freio de estacionamento associado."]'::jsonb,'["paquímetro/micrômetro","relógio comparador","torquímetro"]'::jsonb,'{}'::jsonb,'PartSouq 313 903.662 América Latina lista A9024230312/0412/0512/0612 com cortes por eixo traseiro.','{"seed":"sprinter_w903_chassis_v1","confidence":"axle_cutoff_required","sources":[{"label":"PartSouq 313 903.662 Latin America 2009","url":"https://partsouq.com/es/catalog/genuine/parts?c=Mercedes-Benz&gid=727&q=8AC903662AE024746"},{"label":"PartSouq 313 903.662 Latin America 2012","url":"https://partsouq.com/en/catalog/genuine/parts?c=Mercedes-Benz&gid=736&q=8AC903662CE061397"}]}'::jsonb),
('brakes','Pastilhas de freio traseiras','jogo de pastilha traseira','A0044202720 / A0044202420 / A0034201720 / A0044202520',null,'Dentro das pinças do eixo traseiro.','Geram atrito contra o disco traseiro para frenagem.','["ruido traseiro ao frear","aviso de desgaste","desgaste desigual","freio traseiro fraco"]'::jsonb,'["O 903 usa diferentes jogos conforme pinça/fornecedor e corte de eixo.","Confirmar a pastilha instalada antes da compra.","Verificar mecanismo do freio de estacionamento e guias da pinça."]'::jsonb,'["ferramenta de recuo de pistão","torquímetro","paquímetro"]'::jsonb,'{}'::jsonb,'PartSouq 903.662 latino-americano mostra A0044202720 em versão tardia e outras famílias no W903; conferir pinça/eixo.','{"seed":"sprinter_w903_chassis_v1","confidence":"brake_vendor_variant","sources":[{"label":"PartSouq 313 903.662 Latin America 2009","url":"https://partsouq.com/es/catalog/genuine/parts?c=Mercedes-Benz&gid=727&q=8AC903662AE024746"},{"label":"PartSouq W903 brake family","url":"https://partsouq.com/en/catalog/genuine/diagram?c=MB201810&number=A0004210818"}]}'::jsonb),
('brakes','Sensor de desgaste das pastilhas','sensor de desgaste de freio','A9015400017 / A9015400117 / A9015400217 / A9015400317','Bosch 1 987 473 007','Inserido na pastilha conforme sistema, dianteiro e/ou traseiro.','Fecha/abre o circuito de aviso quando a pastilha atinge o limite de desgaste.','["aviso de pastilha aceso","aviso permanece após troca","fio rompido próximo à roda"]'::jsonb,'["Escolher o sensor conforme jogo de pastilhas/pinça instalado.","Inspecionar chicote e conector expostos à roda.","O sensor deve ser substituído se foi consumido pelo disco."]'::jsonb,'["multímetro","ferramentas manuais"]'::jsonb,'{}'::jsonb,'PartSouq 903.662 lista sensores A90154000/01/02/0317 conforme conjunto de freio.','{"seed":"sprinter_w903_chassis_v1","confidence":"brake_vendor_variant","sources":[{"label":"PartSouq 313 903.662 Latin America 2009","url":"https://partsouq.com/es/catalog/genuine/parts?c=Mercedes-Benz&gid=727&q=8AC903662AE024746"},{"label":"AUTODOC Bosch wear sensor","url":"https://www.autodoc.co.uk/car-parts/wear-indicator-brake-pads-10731/mercedes-benz/sprinter/sprinter-3-t-platform-chassis-903/17061-313-cdi-4x4-903-612-903-613-903-622-903-623"}]}'::jsonb),
('brakes','Sensor ABS de roda','sensor de velocidade da roda ABS','A9015421117 / A9015421717','HELLA 6PU 358 252-571 / Delphi SS20209','Junto ao cubo/munhão, lendo o anel impulsor da roda.','Mede a velocidade da roda para ABS/controle de estabilidade.','["luz ABS acesa","ABS atuando em baixa velocidade sem necessidade","velocidade de uma roda some no scanner"]'::jsonb,'["Comparar as quatro velocidades no scanner em baixa velocidade.","Inspecionar folga de rolamento, anel reluctor, ferrugem e distância do sensor.","Há referências e comprimentos diferentes por posição; confirmar lado/eixo antes da compra."]'::jsonb,'["scanner com dados ABS","multímetro/osciloscópio","ferramentas de limpeza do alojamento"]'::jsonb,'{"type":"indutivo","pins":2,"common_front_resistance_kohm":1.75}'::jsonb,'Catálogo de aplicação 313 W903 OM611.981 mostra família A9015421117/A9015421717; posição exata deve ser confirmada.','{"seed":"sprinter_w903_chassis_v1","confidence":"position_variant","sources":[{"label":"AUTODOC ABS sensor 313 W903","url":"https://www.autodoc.parts/car-parts/abs-sensor-10138/mercedes-benz/sprinter/sprinter-3-t-box-903/14839-313-cdi-903-663-903-662-903-661"}]}'::jsonb),
('suspension','Pivô de suspensão dianteiro','pivô/bandeja dianteira','A9013331227 / A9013331327 / A9013330627','Lemförder 18875 03 / Febi 23696','Extremidade da bandeja dianteira, ligando-a ao munhão.','Permite articulação da suspensão mantendo a roda posicionada.','["folga e batida na dianteira","desgaste irregular de pneu","direcao imprecisa"]'::jsonb,'["Testar folga com alavanca sem apoiar de forma que masque o movimento.","Conferir coifa e assento cônico.","Existem referências/supersessões; comparar geometria e código antes da compra."]'::jsonb,'["elevador","alavanca de inspeção","extrator de pivô","torquímetro"]'::jsonb,'{}'::jsonb,'Família A9013331227/A9013331327/A9013330627 aparece para Sprinter W903 313 CDI 903.662.','{"seed":"sprinter_w903_chassis_v1","confidence":"catalog_cross_reference","sources":[{"label":"AUTODOC ball joint 903.662","url":"https://www.autodoc.parts/car-parts/support-steering-link-10681/mercedes-benz/sprinter/sprinter-3-t-box-903/14839-313-cdi-903-663-903-662-903-661"}]}'::jsonb),
('steering','Barra axial de direção','barra axial/inner tie rod','A9014600205','TRW JRA540 / Lemförder 27756 01','Entre a caixa de direção e o terminal de direção, eixo dianteiro.','Transmite o movimento da caixa de direção à roda e permite ajuste de convergência.','["folga na direcao","batida em piso irregular","desalinhamento recorrente","desgaste irregular de pneus"]'::jsonb,'["Segurar a roda e distinguir folga axial de terminal, pivô e rolamento.","Após substituição, alinhar a dianteira.","Conferir lado/rosca e comprimento antes da compra."]'::jsonb,'["elevador","chave para barra axial","torquímetro","equipamento de alinhamento"]'::jsonb,'{}'::jsonb,'A9014600205 listado para Sprinter W903 313 CDI 903.662 em catálogos de aplicação.','{"seed":"sprinter_w903_chassis_v1","confidence":"strong_model_reference","sources":[{"label":"AUTODOC A9014600205","url":"https://www.autodoc.es/repuestos/oem/a9014600205"},{"label":"AUTODOC inner tie rod 903.662","url":"https://www.autodoc.parts/car-parts/inner-tie-rod-10298/mercedes-benz/sprinter/sprinter-3-t-box-903/17054-313-cdi-4x4-903-662-903-663"}]}'::jsonb),
('suspension','Amortecedor dianteiro','amortecedor/coluna dianteira','A9013201530',null,'Eixo dianteiro, entre conjunto da roda e carroceria/subchassi.','Controla oscilações da suspensão e mantém o pneu em contato com o solo.','["quique excessivo","vazamento de óleo","instabilidade","batida interna"]'::jsonb,'["Comparar lado esquerdo e direito e inspecionar coxins/batentes.","Mercedes lista A9013201530 em pacote 901-903, mas recomenda checagem de compatibilidade por VIN.","Há suspensão standard/reforçada; confirmar a configuração do veículo."]'::jsonb,'["elevador","ferramenta de suspensão","torquímetro"]'::jsonb,'{}'::jsonb,'Mercedes-Benz pacote original para Sprinter 901-903 inclui A9013201530; peça também encontrada em 903.662 OM611.981.','{"seed":"sprinter_w903_chassis_v1","confidence":"suspension_option_required","sources":[{"label":"Mercedes-Benz Originalteile shock package","url":"https://originalteile.mercedes-benz.de/teilepaket-stossdaempfer-sprinter-901-903-vorderachse/a9018970200"},{"label":"903.662 A9013201530 reference","url":"https://www.desguazon.es/pt/amortecedor-frente-direito-a9013201530-mercedes-benz-sprinter-3-t-furgoneta-b903-1995-2012_cabap23828056/"}]}'::jsonb),
('suspension','Amortecedor traseiro','amortecedor traseiro','A9033200131 / A9013200731','Bilstein 19-064529','Eixo traseiro, entre eixo/chassi conforme montagem.','Controla oscilações do eixo traseiro e estabilidade da carroceria.','["quique traseiro","vazamento","instabilidade carregada","batida no fim de curso"]'::jsonb,'["Há versões de suspensão e capacidade de carga diferentes.","Trocar amortecedores aos pares e inspecionar buchas/parafusos.","Confirmar código físico e opção de suspensão antes da compra."]'::jsonb,'["elevador ou fosso","torquímetro","ferramentas manuais"]'::jsonb,'{}'::jsonb,'Mercedes-Benz lista A9033200131/A9013200731 em pacotes 901-903; Bilstein 19-064529 aparece para 313 W903 2001-2012.','{"seed":"sprinter_w903_chassis_v1","confidence":"suspension_option_required","sources":[{"label":"Mercedes-Benz Originalteile Sprinter 901-903","url":"https://originalteile.mercedes-benz.de/originalteile/teilepakete-van/stossdaempfer-pakete/sprinter-901-903/"},{"label":"Bilstein 19-064529 application","url":"https://www.entregapecas.com.br/ProdutoId_132490,62/SUSPENSAO--DIRECAO--TRACAO/AMORTECEDORES/AMORTECEDOR-SUSP-MERCEDES-BENZ-SPRINTER-3-t-Furgao-B903-313-CDI-903663-903662-903661-EIXO-TRASEIRO-2001-2012.html"}]}'::jsonb)
)
insert into public.v2_vehicle_components(group_code,name,generic_name,oem_brand,oem_part_number,manufacturer_part_number,location_description,function_description,failure_symptoms,diagnostic_notes,required_tools,connector_spec,exploded_view_reference,data_status,source_metadata)
select s.group_code,s.name,s.generic_name,'Mercedes-Benz',s.oem_part_number,s.manufacturer_part_number,s.location_description,s.function_description,s.failure_symptoms,s.diagnostic_notes,s.required_tools,s.connector_spec,s.exploded_view_reference,'estimated',s.source_metadata
from seed s
where not exists (
  select 1 from public.v2_vehicle_components c
  where c.name=s.name and c.source_metadata->>'seed'='sprinter_w903_chassis_v1'
);

insert into public.v2_vehicle_component_applications(component_id,chassis_family,chassis_variant,engine_family,engine_code,model_year_from,model_year_to,notes,fitment_status,source_metadata)
select c.id,'W903','903.662','OM611','OM611.981',2010,2011,
       'Referência técnica para Sprinter 313 CDI W903/903.662 OM611.981. Em freios, transmissão e suspensão existem variações por número de eixo, fornecedor e opção de fábrica; conferir peça física/VIN antes da compra.',
       'candidate',
       jsonb_build_object('vehicle_market','Latin America','source_seed','sprinter_w903_chassis_v1')
from public.v2_vehicle_components c
where c.source_metadata->>'seed'='sprinter_w903_chassis_v1'
  and not exists (
    select 1 from public.v2_vehicle_component_applications a
    where a.component_id=c.id and a.chassis_variant='903.662' and a.engine_code='OM611.981' and a.model_year_from=2010 and a.model_year_to=2011
  );

insert into public.v2_vehicle_component_links(company_id,vehicle_id,component_id,fitment_status,notes)
select p.company_id,p.vehicle_id,c.id,'candidate',
       'CATÁLOGO DE CHASSI/TRANSMISSÃO: referência cadastrada para W903 903.662 OM611.981. Confirmar código físico, número do eixo, fornecedor do freio/câmbio ou opção de suspensão antes de comprar.'
from public.v2_vehicle_technical_profiles p
cross join public.v2_vehicle_components c
where p.chassis_variant='903.662' and p.engine_code='OM611.981'
  and c.source_metadata->>'seed'='sprinter_w903_chassis_v1'
on conflict (company_id,vehicle_id,component_id) do nothing;