-- Fleet brakes/clutch verification V4 — 2026-09-27
-- Corrects Volare A6 front-brake architecture using Fras-le application data,
-- verifies Volare A6 clutch lining and 608 brake linings,
-- and records the unresolved VW 9.150 EOD/OD brake year/variant split.

with src(plate,source_key,source_type,title,publisher,publication_year,source_url,authority_level,applicability_status,access_status,verification_status,notes,source_metadata) as (
 values
 ('MBJ1166','frasle_volare_a6_brakes_v4','application_catalog','Fras-le Product and Application Catalog — Volare A6 brakes','Fras-le',2019,'https://www.fras-le.com/media/1657/fras-le_catalogo_de_productos_y_aplicaciones_.pdf','oem_supplier','exact_model_family_year_range','public_full','verified','Volare A6, 1998+: front PD/102 Varga; rear FD/72 Bendix. Corrects the initial generic front-drum seed.',jsonb_build_object('checked_at','2026-09-27','front_reference','PD/102','front_system','Varga','rear_reference','FD/72','rear_system','Bendix','model_year_from',1998)),
 ('MBJ1166','frasle_volare_a6_clutch_lining_v4','application_catalog','Fras-le clutch lining catalog — Volare A6 MWM Sprint','Fras-le',2016,'https://www.fras-le.com/media/1490/catalog-revestimiento-embragues.pdf','oem_supplier','exact_model_engine_family','public_full','verified','Volare A6 MWM Sprint, all: RC/776, Sachs, 300 x 175 x 3.70 mm, 20/20 holes. Friction lining only, not complete clutch disc/kit.',jsonb_build_object('checked_at','2026-09-27','reference','RC/776','system','Sachs','outer_diameter_mm',300,'inner_diameter_mm',175,'thickness_mm',3.70,'through_holes',20,'countersunk_holes',20)),
 ('BYH8J61','lonaflex_lo608d_brakes_v4','application_catalog','Lonaflex Product and Application Catalog — LO-608 D brakes','Lonaflex / Fras-le',2019,'https://fras-le.com/media/1661/lonaflex_catalogo_de_productos_y_aplicaciones_.pdf','oem_supplier','exact_model_year_range','public_full','verified','LO-608 D, 1972-1980: L-522 front/rear, MB system. User vehicle year 1975 is inside catalog range; installed hardware still requires confirmation.',jsonb_build_object('checked_at','2026-09-27','reference_front','L-522','reference_rear','L-522','system','MB','year_from',1972,'year_to',1980)),
 ('CPI6C79','frasle_vw9150_bus_brake_variant_audit_v4','application_catalog','Fras-le Product and Application Catalog — VW 9-150 bus brake variants','Fras-le',2019,'https://www.fras-le.com/media/1657/fras-le_catalogo_de_productos_y_aplicaciones_.pdf','oem_supplier','variant_year_conflict','public_full','verified','VW 9-150 OD bus 2003+: FD/58 front, FD/59 rear, Master. VW 9-150 EOD bus 2006+: FD/59 front/rear, Master. User bus is 2005 and EOD identity remains application-derived, so no lining is promoted.',jsonb_build_object('checked_at','2026-09-27','vehicle_year',2005,'purchase_gate','physical brake lining/hardware or authoritative chassis build data'))
)
insert into public.v2_vehicle_technical_sources(company_id,vehicle_id,source_key,source_type,title,publisher,publication_year,source_url,authority_level,applicability_status,access_status,verification_status,notes,source_metadata)
select v.company_id,v.id,s.source_key,s.source_type,s.title,s.publisher,s.publication_year,s.source_url,s.authority_level,s.applicability_status,s.access_status,s.verification_status,s.notes,s.source_metadata
from src s join public.v2_vehicles v on upper(replace(v.plate,'-',''))=s.plate
on conflict(company_id,vehicle_id,source_key) do update set source_type=excluded.source_type,title=excluded.title,publisher=excluded.publisher,publication_year=excluded.publication_year,source_url=excluded.source_url,authority_level=excluded.authority_level,applicability_status=excluded.applicability_status,access_status=excluded.access_status,verification_status=excluded.verification_status,notes=excluded.notes,source_metadata=excluded.source_metadata,updated_at=now();

-- Volare A6: initial generic front drum components become not-applicable at vehicle level.
update public.v2_vehicle_component_links l set fitment_status='not_applicable',notes=concat_ws(' | ',nullif(l.notes,''),'Corrected V4: Fras-le lists A6 1998+ front PD/102 Varga disc-pad architecture.'),updated_at=now()
from public.v2_vehicles v,public.v2_vehicle_components c where l.vehicle_id=v.id and l.component_id=c.id and v.plate='MBJ1166' and c.id in ('86d1b31a-5556-47c9-8a9e-3b7bc97b1772'::uuid,'d9eac7dd-f340-4df7-b960-db5e4d8d1cc2'::uuid,'c454f5ad-2f08-4033-b639-0597cc62c789'::uuid);
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('vehicle_specific_conflict','MBJ1166 front brake superseded by Fras-le PD/102 Varga application','conflict_source_key','frasle_volare_a6_brakes_v4','do_not_use_for_MBJ1166',true),updated_at=now() where c.id in ('86d1b31a-5556-47c9-8a9e-3b7bc97b1772'::uuid,'d9eac7dd-f340-4df7-b960-db5e4d8d1cc2'::uuid,'c454f5ad-2f08-4033-b639-0597cc62c789'::uuid);
update public.v2_vehicle_component_links l set fitment_status='not_applicable',notes=concat_ws(' | ',nullif(l.notes,''),'Parent front-drum seed not applicable after Volare A6 Fras-le brake correction V4.'),updated_at=now()
from public.v2_vehicles v,public.v2_vehicle_components c where l.vehicle_id=v.id and l.component_id=c.id and v.plate='MBJ1166' and c.source_metadata->>'parent_component_id' in ('86d1b31a-5556-47c9-8a9e-3b7bc97b1772','d9eac7dd-f340-4df7-b960-db5e4d8d1cc2','c454f5ad-2f08-4033-b639-0597cc62c789');

update public.v2_vehicle_components c set oem_brand='Fras-le',manufacturer_part_number='FD/72',data_status='verified',source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('verification_source_key','frasle_volare_a6_brakes_v4','catalog_reference_verified',true,'physical_fitment_verified',false,'brake_system','Bendix','application','Volare A6 1998+ rear'),updated_at=now() where c.id='588baf92-10ec-461d-8833-3de8f425ca3e'::uuid;

insert into public.v2_vehicle_components(group_code,name,generic_name,oem_brand,manufacturer_part_number,location_description,function_description,data_status,component_type,replacement_notes,source_metadata)
select 'brakes','Pastilha de freio dianteira Fras-le PD/102','pastilha de freio dianteira','Fras-le','PD/102','Freio dianteiro, sistema Varga','Material de atrito do freio a disco dianteiro','verified','consumable',jsonb_build_array('Aplicacao confirmada para Volare A6 1998+','Conferir pinça/disco instalados'),jsonb_build_object('seed','fleet_brakes_clutch_verification_v4','verification_source_key','frasle_volare_a6_brakes_v4','catalog_reference_verified',true,'physical_fitment_verified',false,'brake_system','Varga')
where not exists(select 1 from public.v2_vehicle_components c where c.manufacturer_part_number='PD/102' and c.source_metadata->>'verification_source_key'='frasle_volare_a6_brakes_v4');

insert into public.v2_vehicle_components(group_code,name,generic_name,oem_brand,location_description,function_description,data_status,component_type,replacement_notes,source_metadata)
select x.group_code,x.name,x.generic_name,x.oem_brand,x.location_description,x.function_description,'reference_pending','part',jsonb_build_array('Arquitetura inferida da aplicacao de pastilha Varga; codigo/medida exatos ainda nao verificados'),jsonb_build_object('seed','fleet_brakes_clutch_verification_v4','verification_source_key','frasle_volare_a6_brakes_v4','architecture_inferred_from_pad_application',true,'physical_fitment_verified',false,'orderable',false)
from (values ('brakes','Disco de freio dianteiro Volare A6 — codigo a confirmar','disco de freio dianteiro','Varga','Cubo/freio dianteiro','Superficie de atrito da pastilha dianteira'),('brakes','Pinca de freio dianteira Volare A6 — codigo a confirmar','pinca de freio dianteira','Varga','Freio dianteiro','Aplica a pastilha ao disco')) as x(group_code,name,generic_name,oem_brand,location_description,function_description)
where not exists(select 1 from public.v2_vehicle_components c where c.name=x.name and c.source_metadata->>'seed'='fleet_brakes_clutch_verification_v4');

insert into public.v2_vehicle_component_applications(component_id,chassis_family,chassis_variant,engine_family,engine_code,model_year_from,notes,fitment_status,source_metadata)
select c.id,'Marcopolo Volare','A6 / MBJ1166','MWM Sprint Euro 2','4.07 TCA',1998,'Front Varga disc-pad architecture from Fras-le catalog; exact installed hardware candidate.','candidate',jsonb_build_object('source_key','frasle_volare_a6_brakes_v4','physical_confirmation_required',true) from public.v2_vehicle_components c where c.source_metadata->>'seed'='fleet_brakes_clutch_verification_v4' and c.group_code='brakes' and not exists(select 1 from public.v2_vehicle_component_applications a where a.component_id=c.id and a.chassis_variant='A6 / MBJ1166');
insert into public.v2_vehicle_component_links(company_id,vehicle_id,component_id,fitment_status,notes)
select v.company_id,v.id,c.id,'candidate','Volare A6 front-brake catalog architecture V4; physical code/measure confirmation required.' from public.v2_vehicles v cross join public.v2_vehicle_components c where v.plate='MBJ1166' and c.source_metadata->>'seed'='fleet_brakes_clutch_verification_v4' and c.group_code='brakes' on conflict(company_id,vehicle_id,component_id) do nothing;

insert into public.v2_vehicle_exploded_views(group_code,chassis_family,chassis_variant,engine_code,assembly_code,title,subtitle,source_name,source_url,image_license_status,verification_status,notes,source_metadata)
select 'brakes','Marcopolo Volare','A6 / MBJ1166','4.07 TCA','MBJ1166-FRONT-DISC-BRAKE-V4','Volare A6 — freio dianteiro Varga corrigido V4','PD/102 confirmada; disco/pinca aguardam codigo exato','Fras-le','https://www.fras-le.com/media/1657/fras-le_catalogo_de_productos_y_aplicaciones_.pdf','reference_only','reference_pending','Substitui a arquitetura generica de tambor dianteiro para MBJ1166.',jsonb_build_object('seed','fleet_brakes_clutch_verification_v4','plate','MBJ1166','source_key','frasle_volare_a6_brakes_v4','official_epc',false) where not exists(select 1 from public.v2_vehicle_exploded_views ev where ev.assembly_code='MBJ1166-FRONT-DISC-BRAKE-V4');
with tv as (select id from public.v2_vehicle_exploded_views where assembly_code='MBJ1166-FRONT-DISC-BRAKE-V4'),items as (select c.id,c.name,case when c.manufacturer_part_number='PD/102' then '01' when c.name like 'Disco%' then '02' else '03' end item_number,case when c.manufacturer_part_number='PD/102' then 'verified' else 'reference_pending' end exactness from public.v2_vehicle_components c where c.source_metadata->>'seed'='fleet_brakes_clutch_verification_v4' and c.group_code='brakes')
insert into public.v2_vehicle_exploded_view_items(exploded_view_id,component_id,item_number,quantity,component_type,position_note,exactness_status,source_metadata)
select tv.id,i.id,i.item_number,case when i.item_number='01' then 1 else 2 end,'part',case when i.item_number='01' then 'Catalog reference PD/102' else 'Structural component; exact code pending' end,i.exactness,jsonb_build_object('source_key','frasle_volare_a6_brakes_v4') from tv cross join items i where not exists(select 1 from public.v2_vehicle_exploded_view_items e where e.exploded_view_id=tv.id and e.component_id=i.id);

-- Volare A6 clutch friction lining RC/776, not complete disc.
insert into public.v2_vehicle_components(group_code,name,generic_name,oem_brand,manufacturer_part_number,location_description,function_description,data_status,component_type,dimensions_spec,replacement_notes,source_metadata)
select 'transmission','Revestimento de embreagem Fras-le RC/776','revestimento/lona do disco de embreagem','Fras-le','RC/776','Disco de embreagem','Material de atrito do disco; nao equivale ao disco/kit completo','verified','consumable',jsonb_build_object('outer_diameter_mm',300,'inner_diameter_mm',175,'thickness_mm',3.70,'through_holes',20,'countersunk_holes',20,'system','Sachs'),jsonb_build_array('Volare A6 MWM Sprint todos','Confirmar conjunto instalado antes de rebitagem/compra'),jsonb_build_object('seed','fleet_brakes_clutch_verification_v4','verification_source_key','frasle_volare_a6_clutch_lining_v4','catalog_reference_verified',true,'physical_fitment_verified',false,'orderable',false) where not exists(select 1 from public.v2_vehicle_components c where c.manufacturer_part_number='RC/776' and c.source_metadata->>'verification_source_key'='frasle_volare_a6_clutch_lining_v4');
insert into public.v2_vehicle_component_applications(component_id,chassis_family,chassis_variant,engine_family,engine_code,notes,fitment_status,source_metadata)
select c.id,'Marcopolo Volare','A6 / MBJ1166','MWM Sprint Euro 2','4.07 TCA','Fras-le RC/776 catalog application; lining only.','candidate',jsonb_build_object('source_key','frasle_volare_a6_clutch_lining_v4','physical_confirmation_required',true) from public.v2_vehicle_components c where c.source_metadata->>'verification_source_key'='frasle_volare_a6_clutch_lining_v4' and not exists(select 1 from public.v2_vehicle_component_applications a where a.component_id=c.id and a.chassis_variant='A6 / MBJ1166');
insert into public.v2_vehicle_component_links(company_id,vehicle_id,component_id,fitment_status,notes)
select v.company_id,v.id,c.id,'candidate','RC/776 fits Volare A6 MWM Sprint family; confirm installed clutch.' from public.v2_vehicles v cross join public.v2_vehicle_components c where v.plate='MBJ1166' and c.source_metadata->>'verification_source_key'='frasle_volare_a6_clutch_lining_v4' on conflict(company_id,vehicle_id,component_id) do nothing;
with tv as (select id from public.v2_vehicle_exploded_views where assembly_code='MBJ1166-transmission-STRUCT-V1' limit 1),c as (select id from public.v2_vehicle_components where source_metadata->>'verification_source_key'='frasle_volare_a6_clutch_lining_v4')
insert into public.v2_vehicle_exploded_view_items(exploded_view_id,component_id,item_number,quantity,component_type,position_note,exactness_status,source_metadata)
select tv.id,c.id,'CAT-CLUTCH-RC776',1,'consumable','Catalog lining reference; complete hardware separate','verified',jsonb_build_object('source_key','frasle_volare_a6_clutch_lining_v4') from tv cross join c where not exists(select 1 from public.v2_vehicle_exploded_view_items e where e.exploded_view_id=tv.id and e.component_id=c.id);

-- Mercedes 608 1975: L-522 front/rear for LO-608D 1972-1980.
update public.v2_vehicle_components c set oem_brand='Lonaflex',manufacturer_part_number='L-522',data_status='verified',source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('verification_source_key','lonaflex_lo608d_brakes_v4','catalog_reference_verified',true,'physical_fitment_verified',false,'application','LO-608 D 1972-1980','brake_system','MB','purchase_gate','confirm installed brake before purchase'),updated_at=now() where c.id in ('911eaa87-9c9b-433c-9607-7072dcd90e3b'::uuid,'22186b4d-a1e1-470e-beea-ad1af508a9a6'::uuid);

-- VW 9.150 bus: exact catalog split conflicts with current 2005/EOD-derived identity; record but do not promote.
update public.v2_vehicle_technical_profiles p set source_metadata=coalesce(p.source_metadata,'{}'::jsonb)||jsonb_build_object('brake_catalog_variant_audit_v4',jsonb_build_object('source_key','frasle_vw9150_bus_brake_variant_audit_v4','vehicle_year',2005,'OD_2003plus',jsonb_build_object('front','FD/58','rear','FD/59','system','Master'),'EOD_2006plus',jsonb_build_object('front','FD/59','rear','FD/59','system','Master'),'status','unresolved_year_variant_conflict','purchase_gate','physical brake lining/hardware or authoritative chassis build data required')),updated_at=now() from public.v2_vehicles v where p.vehicle_id=v.id and v.plate='CPI6C79';
update public.v2_vehicle_components c set source_metadata=coalesce(c.source_metadata,'{}'::jsonb)||jsonb_build_object('catalog_candidate_source_key','frasle_vw9150_bus_brake_variant_audit_v4','catalog_candidates',case when c.id='f7f09a76-8a38-420c-98da-b10b3e3ac41e'::uuid then jsonb_build_array('FD/58 OD 2003+','FD/59 EOD 2006+') else jsonb_build_array('FD/59 OD 2003+','FD/59 EOD 2006+') end,'promotion_blocked_reason','vehicle is 2005 while Fras-le EOD row starts 2006; current EOD identity not physically confirmed'),updated_at=now() where c.id in ('f7f09a76-8a38-420c-98da-b10b3e3ac41e'::uuid,'3a6fb060-7167-4bc9-b0f3-e74797fb6d5a'::uuid);

update public.v2_vehicle_technical_profiles p set source_metadata=coalesce(p.source_metadata,'{}'::jsonb)||jsonb_build_object('brakes_clutch_research_version','v4','brakes_clutch_reviewed_at','2026-09-27','catalog_correction_policy','vehicle link not_applicable preferred over deleting historical seed'),updated_at=now() from public.v2_vehicles v where p.vehicle_id=v.id and v.plate in ('MBJ1166','BYH8J61','CPI6C79');
